CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  openid VARCHAR(64) UNIQUE,
  email VARCHAR(128) UNIQUE,
  password_hash VARCHAR(255),
  nickname VARCHAR(64),
  avatar VARCHAR(512),
  bio VARCHAR(512) DEFAULT '' COMMENT '个人简介',
  goals VARCHAR(1024) DEFAULT '' COMMENT '近期目标',
  skills VARCHAR(1024) DEFAULT '' COMMENT '技能标签（逗号分隔）',
  interests VARCHAR(1024) DEFAULT '' COMMENT '兴趣爱好（逗号分隔）',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS schedule (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  category_id VARCHAR(64) NULL,
  priority INT NOT NULL DEFAULT 1,
  remark TEXT NULL,
  location VARCHAR(255) NULL,
  completed TINYINT(1) NOT NULL DEFAULT 0,
  remind_at TIME NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_schedule_user_date (user_id, date),
  CONSTRAINT fk_schedule_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS moment (
  id INT AUTO_INCREMENT PRIMARY KEY,
  user_id INT NOT NULL,
  content TEXT NOT NULL,
  date DATE NOT NULL,
  time TIME NOT NULL,
  related_schedule_id INT NULL,
  image_urls JSON NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_moment_user_date (user_id, date),
  CONSTRAINT fk_moment_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
  CONSTRAINT fk_moment_schedule FOREIGN KEY (related_schedule_id) REFERENCES schedule(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
